export const SLASH_BLOCKS = [
  { g:'Text',      ic:'¶',  n:'Paragraph',       d:'A plain text block.',           ins:'\n' },
  { g:'Text',      ic:'T',  n:'Heading 1',        d:'Big important heading.',        ins:'\n# ' },
  { g:'Text',      ic:'T',  n:'Heading 2',        d:'Secondary heading.',            ins:'\n## ' },
  { g:'Text',      ic:'T',  n:'Heading 3',        d:'Smaller heading.',              ins:'\n### ' },
  { g:'Text',      ic:'T',  n:'Heading 4',        d:'Smallest heading.',             ins:'\n#### ' },
  { g:'Text',      ic:'≡',  n:'Bulleted List',    d:'Simple bulleted list.',         ins:'\n- ' },
  { g:'Text',      ic:'1',  n:'Numbered List',    d:'Numbered ordered list.',        ins:'\n1. ' },
  { g:'Text',      ic:'—',  n:'Divider',          d:'Horizontal line.',              ins:'\n\n---\n\n' },
  { g:'Text',      ic:'❝',  n:'Blockquote',       d:'Highlight a quote.',            ins:'\n> ' },
  { g:'Text',      ic:'📣', n:'Callout',          d:'Highlight important content.',  ins:'\n> [!NOTE]\n> ' },
  { g:'Structure', ic:'⊞',  n:'Table',            d:'Simple table.',                 ins:'\n| Col 1 | Col 2 | Col 3 |\n|-------|-------|-------|\n| Cell  | Cell  | Cell  |\n' },
  { g:'Structure', ic:'{}', n:'Code Block',       d:'Fenced code block.',            ins:'\n```\ncode here\n```\n' },
  { g:'Structure', ic:'`',  n:'Inline Code',      d:'Inline code span.',             ins:'`code`' },
  { g:'Structure', ic:'≣',  n:'Table of Contents',d:'List of headings.',             ins:'\n## Table of Contents\n\n- [Section 1](#section-1)\n- [Section 2](#section-2)\n\n' },
  { g:'Structure', ic:'▶',  n:'Collapsible H1',   d:'Collapsible main heading.',     ins:'\n<details>\n<summary>Section</summary>\n\nContent here\n\n</details>\n' },
  { g:'Structure', ic:'▶',  n:'Collapsible H2',   d:'Collapsible secondary.',        ins:'\n<details>\n<summary>Section</summary>\n\nContent\n\n</details>\n' },
  { g:'Structure', ic:'⊟',  n:'Two Columns',      d:'Two-column layout.',            ins:'\n| Left | Right |\n|------|-------|\n|      |       |\n' },
  { g:'Insert',    ic:'📅', n:'Date',             d:"Today's date.",                 ins: new Date().toISOString().split('T')[0] },
  { g:'Insert',    ic:'🔔', n:'Reminder',         d:'Reminder block.',               ins:'\n> [!REMINDER]\n> Date: YYYY-MM-DD\n> Note: \n' },
  { g:'Insert',    ic:'📄', n:'Page Break',       d:'Page separator.',               ins:'\n\n---\n*— Page Break —*\n\n---\n\n' },
  { g:'Insert',    ic:'🗂', n:'Project',          d:'New project block.',            ins:'\n## Project: [Name]\n**Status:** Active\n**Priority:** High\n**Owner:** \n**Deadline:** \n\n### Objectives\n- \n\n### Key Results\n- \n' },
  { g:'Insert',    ic:'📊', n:'Inline Database',  d:'Database inside this page.',    ins:'\n| # | Name | Status | Priority | Date |\n|---|------|--------|----------|------|\n| 1 |      |        |          |      |\n' },
  { g:'Insert',    ic:'🧠', n:'Entity Mention',   d:'Reference dept/project.',       ins:'[[' },
]
